apple/cups

.mailmap

This MailMap will ensure correct GitHub attribution for Michael R Sweet

Add a mailmap for correct work attribution

---

doc/de/index.html.in
locale/cups_de.po

I have reviewed the translations and made it more complete, some minor fixes

updated, more complete german translation

---

man/lpinfo.man

I already asked on cups-devel mailing list but without answer, so I am contacting you this way https://www.cups.org/pipermail/cups-devel/2016-April/016827.html

Update lpinfo.man - removed -U username

---

templates/de/choose-device.tmpl
templates/de/modify-printer.tmpl

I added some missing translation in german template.
greetings!

add some missing translation

---

config-scripts/cups-startup.m4
config.h.in
configure
scheduler/client.h
scheduler/conf.c
scheduler/conf.h
scheduler/cupsd.h
scheduler/listen.c
scheduler/main.c
vcnet/config.h
xcode/config.h

I took this as a reference:
https://bugs.launchpad.net/upstart/+bug/1276713
But rewrote major chunks of it, to rebase onto the latest CUPS, fix bugs, clean up junk, make upstart support configurable, and refactor the general "on demand" code, so I didn't have to duplicate it yet again.
Tested on Chromium OS.
I will try to figure out how to CC Till, but I don't know GitHub that well.

Add Upstart socket activation support

---

locale/cups_zh_CN.po

Not sure if there's anything else to do... Haven't tested it out yet.

locale: introduce cups_zh_CN.po

---

test/ippserver.c

Fix : dead lock when there is already an active job

---

locale/cups_fr.po

This patch provides an update of cups_fr.po : it adds several strings and fixes few of the previous ones.
There are still a lot of untranslated strings. However I think it's a good first step.
Do you think it's mergeable? Do you want more french translations?

Update french translations

---

cups/request.c

Found some if statements which are nested unnecessarily.

Remove unnecessary nesting in if statements.

---

templates/fr/jobs-header.tmpl

Fix typo in french translation

---

scheduler/log.c

Same as pull request from Lutz Heermann, but for PageLog.

Respect PageLog configuration when compiled with journald

---

templates/fr/add-class.tmpl
templates/fr/add-printer.tmpl
templates/fr/admin.tmpl
templates/fr/choose-device.tmpl
templates/fr/choose-model.tmpl
templates/fr/choose-uri.tmpl
templates/fr/class-confirm.tmpl
templates/fr/class.tmpl
templates/fr/classes-header.tmpl
templates/fr/classes.tmpl
templates/fr/help-header.tmpl
templates/fr/job-moved.tmpl
templates/fr/jobs-header.tmpl
templates/fr/jobs.tmpl
templates/fr/printer-default.tmpl
templates/fr/printer.tmpl

Correct typos for French_France

---

locale/cups_zh_CN.po

- Just general completion.
- One typo introduced from my last submission was fixed.

locale/zh_CN: complete translation

---

doc/ru/index.html.in

So it matches the source/template file

Remove newline

---

cups/adminutil.c

Skip previous /admim/log location rules as well.

Fix /admin/log section

---

templates/jobs.tmpl

Fixes error:
E [28/Nov/2019:16:55:51 +0100] [CGI] Saw EOF, expected \':\'!
E [28/Nov/2019:16:55:51 +0100] [CGI] Saw EOF, expected \'}\'!
E [28/Nov/2019:16:55:51 +0100] [CGI] Saw EOF, expected \'}\'!
E [28/Nov/2019:16:55:51 +0100] [CGI] Saw EOF, expected \'}\'!

Fix error in jobs template

---

scheduler/client.c

Fix bug that removes language instead of country code

---

cups/snprintf.c

Prevent writing to NULL if buffer is NULL

---

backend/usb-darwin.c

Add the upstream changes to darwin's fork

Sync usb-darwin to upstream

---

templates/choose-model.tmpl

Cherry picked from https://github.com/OpenPrinting/cups/pull/242

CUPS Web UI: Fix uninitialized variable during driver selection (#242)

---

scheduler/job.c

Cherry picked from https://github.com/OpenPrinting/cups/commit/17ee0b4f9c5f312ae7099e7627aba2b5e6ed0c8d

Expand whitelist for use of "offline-report"
