- doc/es/index.html.in
See the Debian bug: https://bugs.debian.org/821788 from Santiago Vila:
> The file doc/es/index.html.in is a translation of doc/index.html.in, but gerunds like "Using Network Printers" have been translated as "Usando [...]" (Spanish gerund, which is not the same as English gerund). English gerund is a noun, so it should be translated as such.
> Fix spanish gerunds in index.html

- backend/dnssd.c
Add missing semicolon between printer model and command
Closes: #4835
> Fix malformed device-id for printers found by dnssd

- _layouts/default.html
- _layouts/post.html
- _layouts/sub.html
The SSL certificate on the lists server doesn't include lists.cups.org
yet.
> Don't use https for links to lists.cups.org

- man/backend.man
- man/client.conf.man.in
- man/cups-lpd.man.in
- man/cupsd.conf.man.in
On https://bugs.debian.org/838854, Helge Kreutzmann <debian@helgefjell.de> reported some manpage formatting inconsistencies, which I've hereby converted to the source groff format.
> Fix some manpage formatting inconsistencies

- templates/es/jobs.tmpl
Add missing closures and reprint button in templates/es/jobs.tmpl. Before this completed job list output was broken for Spanish language.
> Fix closures and button in templates/es/jobs.tmpl

- systemv/cupstestppd.c
Due to the lack of a length specifier in a `sscanf` used to read the PPD `PSVersion` field, a malicious PPD file can overflow the `junkstr` `char` array in a classic buffer overflow scenario. Since the `\n` character is also missing from the `sscanf`, it's possible to read multiple lines directly into the buffer.
This patch adds both a maximum length specifier, and stops the `sscanf` reading multiple lines, both of which alone will mitigate this overflow.
Since this is a helper tool and not the main CUPS server, and exploiting this (at least on my machines) is completely blocked by ASLR and Stack Canaries, so I felt OK with submitting this PR publicly. My apologies if this is not acceptable.
> cupstestppd Buffer Overflow

- config-scripts/cups-libtool.m4
Substituting @LIBTOOL@ with 'yes' would result in a lot of console
output (34 GB in my case, before SIGKILL), without getting anything
compiled at all.
Adresses #5050
> configure: don't accidentally set @LIBTOOL@ to 'yes'

- locale/cups_fr.po
This patch adds new translations into french language.
The first line fixes only a missing unbrakable space.
I checked that `msgfmt cups_fr.po` runs without errors (no output, exit value is 0).
> Update french translations

- backend/org.cups.usb-quirks
This adds the respective USB quirk entry needed to fix #5102.
> Add a USB quirk rule for the Kyocera Ecosys P6130cdn (Issue #5102)

- backend/org.cups.usb-quirks
Hi Mike,
Canon MP540 and Samsung ML-2160 Series printers were unable to print fine, when they were connected by usb. Adding these usb quirks solved issues. Would you mind merging it into CUPS project?
> add usb quirks for canon mp540 and Samsung ML-2160 Series

- systemv/lpadmin.c
Rearranging the null checks in lpadmin so that the connection is opened after the printer has been checked. I think it makes more sense to fail if the printer is null before bothering to open an http connection.
> Rearranging order of null checks in lpadmin

- scheduler/cups-driverd.cxx
if return 0, load_ppds won't continue to search other files in current directory.
> consider loop detected to be success

- scheduler/log.c
When cups is compiled against journald access log is written to journal if ErrorLog is set to syslog and the AccesLog settings is ignored.
> Respect AccessLog configuration when compiled against journald.

- cups/ppd-conflicts.c
Without this patch it was taking all constraints into account, not only the ones
regarding the passed option so if you had a conflict somewhere else, every other
single option would be said to be conflicting which doesn't match what the
documentation says this function should do.
> Fix ppdInstallableConflict conflict reporting

- cups/usersys.c
A compile error occurs in `usersys.c` when `HAVE_SSL` is not defined.
This additional ifdef fixes it.
Same as https://github.com/istopwg/ippsample/pull/68
> Fix compile without HAVE_SSL

- locale/cups_de.po
Fixed some discovered typos in `locale/cups_de.po`
> Some typo fixes in the german translation

- doc/help/man-lpoptions.html
- man/lpoptions.man.in
The [man page for lpoptions](https://github.com/apple/cups/blob/afad2da22d1e301c13472e365a58a5179acb9429/doc/help/man-lpoptions.html) mentions a -U username option, to set the username for a printer. This option does not exist in [lpoptions.c](https://github.com/apple/cups/blob/105b26dedeb9cbed2a247bd68167122f73389c87/systemv/lpoptions.c) proper.
> Remove mentions of non-implemented -U option from lpoptions manpage

- scheduler/org.cups.cupsd.service.in
When using socket activation cups daemon can safely exit on idle and be automatically started when it's needed. Using Restart=always prevent this behavior and causes cups daemon constantly restarting itself instead of exiting. Users reported[1] that Restart=on-failure was enough to fix issues[2] so Restart=always may be unnecessary and harmful.
[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861470
[2] https://github.com/apple/cups/issues/5263
> Allow cupsd daemon to exit on idle

- doc/help/spec-command.html
Hey, this trivial patch fixes a typo in the CUPS Command File example.  I wasted several hours on this before realizing the example was wrong.
> Fix typo in example (cupsCommand -> cupsCommands)

- scheduler/main.c
There's only one line that makes the build fail under `-Werror=maybe-unitialized` :
```
Compiling listen.c...
cc  -fPIC -g -fstack-protector -D_GNU_SOURCE -I.. -D_CUPS_SOURCE -isystem /usr/include/mit-krb5 -Wdate-time -D_FORTIFY_SOURCE=2 -isystem /usr/include/mit-krb5 -g -O2 -fdebug-prefix-map=/tmp/reprotest.wwqjgR/const_build_path=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -D_FORTIFY_SOURCE=2 -D_REENTRANT -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -Werror -Wno-error=deprecated-declarations -Wall -Wno-format-y2k -Wunused -Wno-unused-result …
```
> Fix service_idle_exit build issue with -Werror=maybe-unitialized

- locale/cups_ru.po
msgfmt -c cups_ru.po gave some warnings about some ending \n that was in the source strings.
> Remove some newlines from cups_ru.po

- cups/ppd-cache.c
Clang-7 complains that there is a cast from unsigned (ipp_finishing_t which is an enum) to signed (int).  Perform an explicit cast since this should always be safe as long as ipp_finsihing_t is not too large.
> Make explicit cast from enum to integer

- test/run-stp-tests.sh
As identified in https://github.com/apple/cups/issues/5576#issuecomment-490148791, some files cannot be found in tests.
Indeed, the generated filters look for some example files in `test/` while they moved to `examples/` between v2.3b7 and v2.3b8.
> Test: Fix *topdf filters to find the examples in the correct path

- scheduler/job.c
While backporting the PreserveJobHistory fix to Ubuntu 16.04 I noticed there probably is a typo. Adjusted syntax to be consistent with next if.
> Fix parentheses in cupsdCleanJobs.

- scheduler/auth.c
scheduler/auth.c has static to64() function if LIBPAM is unavailable, but there is no part using it. To calm -Wunused-functions, I removed to64(). Please could you consider?
> remove unused to64() from scheduler/auth.c to calm warning for -Wunused-functions

- tools/ippeveprinter.c
Swapped branches of #ifdef HAVE_SSL conditional
Can not be built if HAVE_SSL is undefined because of missing "securi" identifier.
> Swapped branches of HAVE_SSL condition

- config-scripts/cups-defaults.m4
- configure
Members of the wheel group are able to gain system privileges, so for intents and purposes of CUPS it can be considered a system group. This allows to use privileged operations in the web interface as the user instead of root for members of the wheel group. 
Fedora Linux applies this by default: https://unix.stackexchange.com/questions/235477/cups-add-printer-page-returns-forbidden-on-web-interface
> Add wheel to system groups

- cgi-bin/var.c
Hi,
I have a report in Fedora from ABRT tool https://bugzilla.redhat.com/show_bug.cgi?id=1720688 , which caught SIGSEGV in CUPS when user tried to add new printer by CUPS web ui.
It seems the element, which is tried to dup, is NULL. The check if it is NULL should cover it.
Does the patch look good? Please let me know if I can enhance something.
> SIGSEGV in CUPS web ui when adding a printer

- cups/ipp-support.c
When enumvalue is 101 and attrname is "finsishings-supported"
we were getting the memory after ipp_finishings_vendor
in the ipp_job_collation_types array.
> Off by one error in ipp_finishings_vendor

- backend/usb-darwin.c
- scheduler/sysman.c
bzero has been deprecated by POSIX 2008. It recommends the use of memset
instead.
> treewide: Replace bzero with memset

- cups/tlscheck.c
- ppdc/ppdc.cxx
- ppdc/ppdhtml.cxx
- ppdc/ppdi.cxx
- ppdc/ppdmerge.cxx
- ppdc/ppdpo.cxx
Almost every non-returning function has this qualifier, but not all. This should properly define them all as well as shrink the final binary a little bit.
> Add _CUPS_NORETURN to missing functions

- cgi-bin/template.c
- cgi-bin/var.c
- cups/auth.c
- cups/getdevices.c
- cups/ipp-file.c
- cups/pwg-media.c
- cups/tls-gnutls.c
- filter/common.c
- filter/rastertohp.c
- scheduler/main.c
- scheduler/util.c
- systemv/cancel.c
- systemv/cupstestppd.c
- systemv/lpstat.c
- tools/ippeveps.c
Some of the code is either dead code, redundant, or always true. Meaning they do not do anything since the cases were already dealt with in earlier parts of the code. It would be best to remove this code.
Note that some of the code removal required a tiny bit of refactoring.
> Remove redundant code

- packaging/cups.list.in
Cherry picked from OpenPrinting CUPS
> Fix path to libcupsimage.so.2 in EPM packaging

- scheduler/log.c
Cherry picked from https://github.com/OpenPrinting/cups/pull/154
> scheduler/log.c: Use [Job N] even for syslog

- ppdc/ppdc-source.cxx
- ppdc/ppdc.cxx
The gamma and density arguments are passed in the wrong order. This patch fixes this.
> Fix swapped arguments

- cups/snprintf.c
> Add buffer range check.

- scheduler/ipp.c
> Change job state to IPP_JOB_HELD when job is restarted with appropriate job-held-until attribute.
